import { ref } from "vue";

export const services = ref([
  {
    title: "Web Development",
    icon: "mdi-web",
    description:
      "Creating responsive and modern websites to boost your online presence.",
    detailedDescription:
      "We build custom, responsive websites that work flawlessly across all devices. From corporate websites to complex web applications, we use cutting-edge technologies like Vue.js, React, and modern CSS frameworks to deliver fast, SEO-friendly, and visually stunning solutions that drive results.",
    features: [
      "Custom website design and development",
      "Responsive and mobile-first approach",
      "Progressive Web Apps (PWA)",
      "Single Page Applications (SPA)",
      "Performance optimization",
      "Cross-browser compatibility",
    ],
    technologies: [
      "Vue.js",
      "React",
      "Nuxt.js",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
    ],
    deliverables: [
      "Fully responsive website",
      "Source code and documentation",
      "Content Management System (CMS) integration",
      "Analytics and tracking setup",
    ],
    timeline: "4-8 weeks (depending on complexity)",
    link: "/services/web-development",
  },
  {
    title: "UI/UX Design",
    icon: "mdi-pencil-ruler",
    description: "Designing visually appealing and user-friendly interfaces.",
    detailedDescription:
      "Our design team crafts intuitive, engaging user experiences that convert visitors into customers. We follow a user-centered design approach, conducting research, creating wireframes, and prototyping interactive designs that align with your brand identity and business goals.",
    features: [
      "User research and persona development",
      "Wireframing and prototyping",
      "Visual design and branding",
      "Interactive prototypes",
      "Usability testing",
      "Design system creation",
    ],
    technologies: [
      "Figma",
      "Adobe XD",
      "Sketch",
      "InVision",
      "Miro",
      "Principle",
    ],
    deliverables: [
      "Complete design mockups",
      "Interactive prototypes",
      "Design system and style guide",
      "User flow diagrams",
      "Design handoff files for developers",
    ],
    timeline: "3-6 weeks (depending on scope)",
    link: "/services/ui-ux-design",
  },
  {
    title: "Mobile App Development",
    icon: "mdi-cellphone",
    description:
      "Building high-performance mobile applications for iOS and Android.",
    detailedDescription:
      "We develop native and cross-platform mobile applications that deliver exceptional user experiences. Whether you need an iOS app, Android app, or both, our team builds scalable, secure, and feature-rich mobile solutions that engage users and drive business growth.",
    features: [
      "Native iOS and Android development",
      "Cross-platform development (React Native, Flutter)",
      "App store submission and optimization",
      "Push notifications and real-time features",
      "Offline functionality",
      "Third-party API integrations",
    ],
    technologies: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Firebase",
      "Expo",
    ],
    deliverables: [
      "Production-ready mobile app",
      "App store deployment",
      "Source code and documentation",
      "Admin panel (if applicable)",
      "Post-launch support",
    ],
    timeline: "8-16 weeks (depending on features)",
    link: "/services/mobile-app-development",
  },
  {
    title: "API & Backend Solutions",
    icon: "mdi-server",
    description: "Creating scalable APIs and robust backend systems.",
    detailedDescription:
      "We architect and develop powerful backend systems and RESTful APIs that serve as the foundation for your applications. Our solutions are built for scale, security, and performance, handling everything from authentication to complex business logic and data processing.",
    features: [
      "RESTful and GraphQL API design",
      "Database design and optimization",
      "Authentication and authorization (OAuth, JWT)",
      "Microservices architecture",
      "Real-time communication (WebSockets)",
      "Third-party integrations (payment gateways, email services)",
    ],
    technologies: [
      "FastAPI",
      "Node.js",
      "Python",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Docker",
    ],
    deliverables: [
      "Fully documented API",
      "Database schema and migrations",
      "API documentation (Swagger/OpenAPI)",
      "Deployment scripts and CI/CD pipeline",
      "Performance and security testing reports",
    ],
    timeline: "6-12 weeks (depending on complexity)",
    link: "/services/api-backend-solutions",
  },
  {
    title: "SEO Optimization",
    icon: "mdi-chart-line",
    description:
      "Improving your search engine rankings and driving organic traffic.",
    detailedDescription:
      "Our SEO specialists optimize your website to rank higher in search engine results, driving qualified organic traffic to your business. We conduct comprehensive audits, implement technical SEO improvements, create content strategies, and build quality backlinks to boost your online visibility.",
    features: [
      "Technical SEO audit and optimization",
      "Keyword research and strategy",
      "On-page SEO optimization",
      "Content optimization and creation",
      "Link building and outreach",
      "Local SEO and Google My Business optimization",
    ],
    technologies: [
      "Google Analytics",
      "Google Search Console",
      "SEMrush",
      "Ahrefs",
      "Screaming Frog",
    ],
    deliverables: [
      "Comprehensive SEO audit report",
      "Keyword research and targeting plan",
      "Technical SEO implementation",
      "Monthly performance reports",
      "Content optimization recommendations",
    ],
    timeline: "Ongoing (3-6 months for significant results)",
    link: "/services/seo-optimization",
  },
  {
    title: "Cloud Solutions",
    icon: "mdi-cloud",
    description: "Providing scalable cloud infrastructure and services.",
    detailedDescription:
      "We help businesses leverage cloud technologies to improve scalability, reduce costs, and increase reliability. From cloud migration to infrastructure setup and optimization, we provide end-to-end cloud solutions using industry-leading platforms like AWS, Google Cloud, and Azure.",
    features: [
      "Cloud architecture design",
      "Cloud migration and deployment",
      "Infrastructure as Code (Terraform, CloudFormation)",
      "Container orchestration (Kubernetes, Docker)",
      "CI/CD pipeline setup",
      "Monitoring and logging solutions",
    ],
    technologies: [
      "AWS",
      "Google Cloud Platform",
      "Azure",
      "Docker",
      "Kubernetes",
      "Terraform",
    ],
    deliverables: [
      "Cloud infrastructure setup",
      "Deployment automation",
      "Monitoring and alerting dashboard",
      "Infrastructure documentation",
      "Cost optimization report",
    ],
    timeline: "4-10 weeks (depending on requirements)",
    link: "/services/cloud-solutions",
  },
  {
    title: "E-Commerce Solutions",
    icon: "mdi-cart",
    description:
      "Building e-commerce platforms tailored for your business growth.",
    detailedDescription:
      "We create comprehensive e-commerce solutions that help you sell online effectively. From product catalogs to checkout flows and payment processing, we build secure, scalable platforms that provide seamless shopping experiences and drive conversions.",
    features: [
      "Custom e-commerce platform development",
      "Shopping cart and checkout optimization",
      "Payment gateway integration (Stripe, PayPal, M-Pesa)",
      "Inventory management system",
      "Order tracking and fulfillment",
      "Customer account management",
    ],
    technologies: [
      "Vue.js",
      "Next.js",
      "Shopify",
      "WooCommerce",
      "Stripe API",
      "FastAPI",
    ],
    deliverables: [
      "Fully functional e-commerce website",
      "Admin dashboard for product management",
      "Payment processing integration",
      "Order management system",
      "Analytics and reporting tools",
    ],
    timeline: "8-14 weeks (depending on features)",
    link: "/services/e-commerce",
  },
]);
